package adapters

import (
	"regexp"
	"strings"
)

// Roles the indexer treats specially. RoleContext events are injected
// boilerplate (rules files, skill bodies, harness caveats): kept in the event
// log but never made searchable, because they repeat in every session and
// drown real matches.
const (
	RoleContext = "context"
	RoleSummary = "summary"
	RoleArchive = "archive"
)

// injectedSpanRe matches harness-injected spans embedded in an otherwise real
// message.
var injectedSpanRe = regexp.MustCompile(`(?s)<system-reminder>.*?</system-reminder>|<INSTRUCTIONS>.*?</INSTRUCTIONS>|<environment_context>.*?</environment_context>|<user_instructions>.*?</user_instructions>|<local-command-caveat>.*?</local-command-caveat>`)

// contextPrefixes mark a message that is wholly injected context.
var contextPrefixes = []string{
	"# AGENTS.md instructions for ",
	"Base directory for this skill:",
	"Caveat: The messages below were generated by the user while running local commands",
}

// StripInjected removes harness-injected spans from a message.
func StripInjected(s string) string {
	return strings.TrimSpace(injectedSpanRe.ReplaceAllString(s, ""))
}

// IsContext reports whether a message is wholly injected context.
func IsContext(s string) bool {
	t := strings.TrimSpace(s)
	for _, p := range contextPrefixes {
		if strings.HasPrefix(t, p) {
			return true
		}
	}
	return false
}

// titleLine returns the first line of s usable as a session title, or "" when
// the message is harness markup or a compaction preamble rather than a prompt.
func titleLine(s string) string {
	for _, ln := range strings.Split(s, "\n") {
		ln = strings.TrimSpace(ln)
		if ln == "" {
			continue
		}
		if strings.HasPrefix(ln, "<") || strings.HasPrefix(ln, "This session is being continued from a previous conversation") {
			return ""
		}
		return ln
	}
	return ""
}
